catalog_films:
    resource: "@CatalogFilmsBundle/Resources/config/routing.yml"
    prefix:   /catalog_films

guest_book:
    resource: "@GuestBookBundle/Resources/config/routing.yml"
    prefix:   /

game_of_thrones_light_and_shadow:
    resource: "@GameOfThronesLightAndShadowBundle/Controller/"
    type:     annotation
    prefix:   /

game_of_thrones_legacy:
    resource: "@GameOfThronesLegacyBundle/Controller/"
    type:     annotation
    prefix:   /

game_of_thrones_mors_westford:
    resource: "@GameOfThronesMorsWestfordBundle/Controller/"
    type:     annotation
    prefix:   /