#catalog_user:
#    resource: "@CatalogUserBundle/Controller/"
#    type:     annotation
#    prefix:   /

catalog_films:
    resource: "@CatalogFilmsBundle/Resources/config/routing.yml"
    prefix:   /catalog_films

guest_book:
    resource: "@GuestBookBundle/Resources/config/routing.yml"
    prefix:   /

game_of_thrones_light_and_shadow:
    resource: "@GameOfThronesLightAndShadowBundle/Controller/"
    type:     annotation
    prefix:   /

game_of_thrones_legacy:
    resource: "@GameOfThronesLegacyBundle/Controller/"
    type:     annotation
    prefix:   /

game_of_thrones_mors_westford:
    resource: "@GameOfThronesMorsWestfordBundle/Controller/"
    type:     annotation
    prefix:   /

#fos_user
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile