parameters:
    catalog_films.helper_method.class: Catalog\FilmsBundle\Helper\HelperMethod
    catalog_films.subscriber.upload_file.class: Catalog\FilmsBundle\Form\EventListener\UploadFileSubscriber

services:
    catalog_films.helper_method:
        class: %catalog_films.helper_method.class%
        arguments: []
        calls:
            - [ setPathUploadFile, ["%upload_file%"] ]

    catalog_films.form.type.film:
        class: Catalog\FilmsBundle\Form\FilmsType
        arguments: [ @catalog_films.helper_method ]
        tags:
           - { name: form.type, alias: film }

#    catalog_films.subscriber.upload_file:
#        class: %catalog_films.subscriber.upload_file.class%
#        arguments: []
#        calls:
#           - [ setHm, [@catalog_films.helper_method] ]
#        tags:
#           - { name: form.event_listener, event: postPersist }