parameters:
#    catalog_films.example.class: Catalog\FilmsBundle\Example

services:
#    catalog_films.example:
#        class: %catalog_films.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
